import {
  FaYoutube,
  FaLinkedinIn,
  FaFacebookF,
  FaInstagram,
  FaTiktok,
  FaXTwitter,
} from "react-icons/fa6";


export const trends = {
   market: [
    {
        id: "1",
        image: "/house.svg",
        sideImg: "/sideman.svg",
        vipImg: "/vip.svg",
        price: "₦28,000",
        dayPrice: "per day",
        standard: "Standard studio apartment per day",
        descriptionHouse: "Very Clean and comfortable area to spend your weekends or holiday with...",
        locationImg: "/location.svg",
        location: "Egbeda, Lagos",
        lUsed: "Local Used",
        auto: "Automatic"
    },
    {
        id: "2",
        image: "/house.svg",
        sideImg: "/sideman.svg",
        vipImg: "/vip.svg",
        price: "₦28,000",
        dayPrice: "per day",
        standard: "Standard studio apartment per day",
        descriptionHouse: "Very Clean and comfortable area to spend your weekends or holiday with...",
        locationImg: "/location.svg",
        location: "Egbeda, Lagos",
        lUsed: "Local Used",
        auto: "Automatic"
    },
    {
      id: "3",
      image: "/benz.svg",
      sideImg: "/sideman.svg",
      vipImg: "/enterprise.svg",
      price: "₦8,000,000",
      standard: "Toyota Camry 2.4 XLE 2008 Blue",
      description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
      descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM",
      locationImg: "/location.svg",
      location: "Abule-Egba, Lagos",
      carImg: "/car.svg",
      lUsed: "Local Used",
      dUsed: "Local Used",
      auto: "Automatic",
      dAuto: "Automatic",
      autoImg: "/automatic.svg",
      meterImg: "/meter.svg",
      meterText: "9500km",
      home: "Home",
      cars: "Cars",
      titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
      bookMark: "/bookmark.svg",
      shareIcon: "/share.svg",
      firstImg: "/productImg.svg",
      secondImg: "/productImg2.svg",
      thirdImg: "/productImg3.svg",
      fourthImg: "/productImg4.svg",
      fifthImg: "/productImg5.svg",
      carDetails: "Car Details",
      more: "Show all",
      dropImg: "/downdrop.svg",
      updropImg: "/dropup.svg",
      reviews: "Reviews (0)",
      hide: true,
      isSold: true,
     specs: {
      eyeImg: "/eye.svg",
      eyeText: "19,000 Views",
      promoteButton: "Promoted",
      postedText: "Posted on March 19th 2023",
      titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
      locationIcon: "/bluLoc.svg",
      locationN: "Abule-Egba, Lagos",
      carImg: "/car.svg",
      dUsed: "Local Used",
      auto: "Automatic",
      dAuto: "Automatic",
      autoImg: "/automatic.svg",
      meterImg: "/meter.svg",
      meterText: "9500km",
      make: "Make",
      makeName: "Toyota",
      model: "Model",
      modelName: "2.4 XLE",
      manufacturing: "Manufacturing Year",
      factoryYear: "2008",
      interior: "Interior Color",
      interiorColor: "Black",
      condition: "Condition",
      conditionTitle: "No Faults",
      color: "Color",
      colorType: "Black",
      seatNo: "No of seats",
      seatCount: "4",
      fuelType: "Fuel Type",
      eletric: "Eletric",
      moreInfo: "More Info",
      infoDescription: "Neatly used Toyota Camry 2.4 XLE 2008. Blue in color and in good condition. Here are some features in the car: Air Conditioning, AM/FM Radio, CD Player, Alloy Wheels, Airbags, Armrests, Cruise Control, Cup Holders, Electric Mirrors, Electric Windows, Front Fog Lamps, Leather Seats, LED Headlights, Parking Assist, Parking Sensors, Sunroof, Traction Control, Xenon Lights",
      storeAdd: "Store Address",
      locationImg: "/location.svg",
      location: "Ajah - Lagos State",
      locationDetails: "24, Shola Martins Streets, Ajah, Lagos",
      deliveryImg: "/truck.svg",
      deliveryBtn: "No delivery",
      workingHour: "Working Hours",
      days: ["Mon", "Tue", "Wed", "Fri"],
      clockImg: "/clock.svg",
      openingHours: "8:30am - 11:00pm",
      availability: "Opened",
      share: "Share",
      whatappImg: "/Whatapp.svg",
      linkedlnImg: "/linkedin.svg",
      facebookImg: "/facebook.svg",
      instaImg: "/gram.svg",
      tiktokImg: "/tiktok.svg",
      twitterImg: "/twitter.svg",
      suggestions: "Suggested For You",
      image: "/benz.svg",
      sideImg: "/sideman.svg",
      vipImg: "/enterprise.svg",
      price: "₦8,000,000",
      standard: "Toyota Camry 2.4 XLE 2008 Blue",
      description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
      descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM",
      reviewImg: "/reviews.svg",
      reviewText: "No Reviews Yet",
      reviewBtn: "Write a Review"
     }
    },
    {
        id: "4",
        image: "/benz.svg",
        sideImg: "/sideman.svg",
        vipImg: "/enterprise.svg",
        price: "₦8,000,000",
        standard: "Toyota Camry 2.4 XLE 2008 Blue",
        description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
        descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM",
        locationImg: "/location.svg",
        location: "Abule-Egba, Lagos",
        carImg: "/car.svg",
        lUsed: "Local Used",
        auto: "Automatic",
        dUsed: "Local Used",
        auto: "Automatic",
        dAuto: "Automatic",
        autoImg: "/automatic.svg",
        meterImg: "/meter.svg",
        meterText: "9500km",
        home: "Home",
        cars: "Cars",
        titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
        bookMark: "/bookmark.svg",
        shareIcon: "/share.svg",
        firstImg: "/productImg.svg",
        secondImg: "/productImg2.svg",
        thirdImg: "/productImg3.svg",
        fourthImg: "/productImg4.svg",
        fifthImg: "/productImg5.svg",
        carDetails: "Car Details",
        more: "Show all",
        dropImg: "/downdrop.svg",
        updropImg: "/dropup.svg",
        reviews: "Reviews (0)",
        hide: true,
        isSold: false,
        specs: {
          eyeImg: "/eye.svg",
          eyeText: "19,000 Views",
          promoteButton: "Promoted",
          postedText: "Posted on March 19th 2023",
          titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
          locationIcon: "/bluLoc.svg",
          location: "Abule-Egba, Lagos",
          carImg: "/car.svg",
          dUsed: "Local Used",
          auto: "Automatic",
          dAuto: "Automatic",
          autoImg: "/automatic.svg",
          meterImg: "/meter.svg",
          meterText: "9500km",
          make: "Make",
          makeName: "Toyota",
          model: "Model",
          modelName: "2.4 XLE",
          manufacturing: "Manufacturing Year",
          factoryYear: "2008",
          interior: "Interior Color",
          interiorColor: "Black",
          condition: "Condition",
          conditionTitle: "No Faults",
          color: "Color",
          colorType: "Blue",
          seatNo: "No of seats",
          seatCount: "4",
          fuelType: "Fuel Type",
          eletric: "Eletric",
          moreInfo: "More Info",
          infoDescription: "Neatly used Toyota Camry 2.4 XLE 2008. Blue in color and in good condition. Here are some features in the car: Air Conditioning, AM/FM Radio, CD Player, Alloy Wheels, Airbags, Armrests, Cruise Control, Cup Holders, Electric Mirrors, Electric Windows, Front Fog Lamps, Leather Seats, LED Headlights, Parking Assist, Parking Sensors, Sunroof, Traction Control, Xenon Lights",
          storeAdd: "Store Address",
          locationImg: "/location.svg",
          location: "Ajah - Lagos State",
          locationDetails: "24, Shola Martins Streets, Ajah, Lagos",
          deliveryImg: "/truck.svg",
          deliveryBtn: "No delivery",
          workingHour: "Working Hours",
          days: ["Mon", "Tue", "Wed", "Fri"],
          clockImg: "/clock.svg",
          openingHours: "8:30am - 11:00pm",
          availability: "Opened",
          share: "Share",
          whatappImg: "/Whatapp.svg",
          linkedlnImg: "/linkedin.svg",
          facebookImg: "/facebook.svg",
          instaImg: "/gram.svg",
          tiktokImg: "/tiktok.svg",
          twitterImg: "/twitter.svg",
          suggestions: "Suggested For You",
          image: "/benz.svg",
          sideImg: "/sideman.svg",
          vipImg: "/enterprise.svg",
          price: "₦8,000,000",
          standard: "Toyota Camry 2.4 XLE 2008 Blue",
          description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
          descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM"
         }
      },
      {
        id: "5",
        image: "/house.svg",
        sideImg: "/nonVip.svg",
        price: "₦28,000",
        dayPrice: "per day",
        standard: "Standard studio apartment per day",
        descriptionHouse: "Very Clean and comfortable area to spend your weekends or holiday with...",
        locationImg: "/location.svg",
        location: "Egbeda, Lagos",
        lUsed: "Local Used",
        auto: "Automatic"
    },
    {
        id: "6",
        image: "/house.svg",
        sideImg: "/nonVip.svg",
        price: "₦28,000",
        dayPrice: "per day",
        standard: "Standard studio apartment per day",
        descriptionHouse: "Very Clean and comfortable area to spend your weekends or holiday with...",
        locationImg: "/location.svg",
        location: "Egbeda, Lagos",
        lUsed: "Local Used",
        auto: "Automatic"
    },
    {
        id: "7",
        image: "/benz.svg",
        sideImg: "/nonVip.svg",
        price: "₦8,000,000",
        standard: "Toyota Camry 2.4 XLE 2008 Blue",
        description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
        descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM",
        locationImg: "/location.svg",
        location: "Abule-Egba, Lagos",
        lUsed: "Local Used",
        auto: "Automatic",
        carImg: "/car.svg",
        dUsed: "Local Used",
        auto: "Automatic",
        dAuto: "Automatic",
        autoImg: "/automatic.svg",
        meterImg: "/meter.svg",
        meterText: "9500km",
        home: "Home",
        cars: "Cars",
        titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
        bookMark: "/bookmark.svg",
        shareIcon: "/share.svg",
        firstImg: "/productImg.svg",
        secondImg: "/productImg2.svg",
        thirdImg: "/productImg3.svg",
        fourthImg: "/productImg4.svg",
        fifthImg: "/productImg5.svg",
        carDetails: "Car Details",
        more: "Show all",
        dropImg: "/downdrop.svg",
        updropImg: "/dropup.svg",
        reviews: "Reviews (0)",
        hide: true,
        isSold: true,
        specs: {
          eyeImg: "/eye.svg",
          eyeText: "19,000 Views",
          promoteButton: "Promoted",
          postedText: "Posted on March 19th 2023",
          titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
          locationIcon: "/bluLoc.svg",
          location: "Abule-Egba, Lagos",
          carImg: "/car.svg",
          dUsed: "Local Used",
          auto: "Automatic",
          dAuto: "Automatic",
          autoImg: "/automatic.svg",
          meterImg: "/meter.svg",
          meterText: "9500km",
          make: "Make",
          makeName: "Toyota",
          model: "Model",
          modelName: "2.4 XLE",
          manufacturing: "Manufacturing Year",
          factoryYear: "2008",
          interior: "Interior Color",
          interiorColor: "Black",
          condition: "Condition",
          conditionTitle: "No Faults",
          color: "Color",
          colorType: "Blue",
          seatNo: "No of seats",
          seatCount: "4",
          fuelType: "Fuel Type",
          eletric: "Eletric",
          moreInfo: "More Info",
          infoDescription: "Neatly used Toyota Camry 2.4 XLE 2008. Blue in color and in good condition. Here are some features in the car: Air Conditioning, AM/FM Radio, CD Player, Alloy Wheels, Airbags, Armrests, Cruise Control, Cup Holders, Electric Mirrors, Electric Windows, Front Fog Lamps, Leather Seats, LED Headlights, Parking Assist, Parking Sensors, Sunroof, Traction Control, Xenon Lights",
          storeAdd: "Store Address",
          locationImg: "/location.svg",
          location: "Ajah - Lagos State",
          locationDetails: "24, Shola Martins Streets, Ajah, Lagos",
          deliveryImg: "/truck.svg",
          deliveryBtn: "No delivery",
          workingHour: "Working Hours",
          days: ["Mon", "Tue", "Wed", "Fri"],
          clockImg: "/clock.svg",
          openingHours: "8:30am - 11:00pm",
          availability: "Opened",
          share: "Share",
          whatappImg: "/Whatapp.svg",
          linkedlnImg: "/linkedin.svg",
          facebookImg: "/facebook.svg",
          instaImg: "/gram.svg",
          tiktokImg: "/tiktok.svg",
          twitterImg: "/twitter.svg",
          suggestions: "Suggested For You",
          image: "/benz.svg",
          sideImg: "/sideman.svg",
          vipImg: "/enterprise.svg",
          price: "₦8,000,000",
          standard: "Toyota Camry 2.4 XLE 2008 Blue",
          description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
          descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM"
         }
      },
      {
        id: "8",
        image: "/benz.svg",
        sideImg: "/nonVip.svg",
        price: "₦8,000,000",
        standard: "Toyota Camry 2.4 XLE 2008 Blue",
        description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
        descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM",
        locationImg: "/location.svg",
        location: "Abule-Egba, Lagos",
        lUsed: "Local Used",
        auto: "Automatic",
        carImg: "/car.svg",
        dUsed: "Local Used",
        auto: "Automatic",
        dAuto: "Automatic",
        autoImg: "/automatic.svg",
        meterImg: "/meter.svg",
        meterText: "9500km",
        home: "Home",
        cars: "Cars",
        titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
        bookMark: "/bookmark.svg",
        shareIcon: "/share.svg",
        firstImg: "/productImg.svg",
        secondImg: "/productImg2.svg",
        thirdImg: "/productImg3.svg",
        fourthImg: "/productImg4.svg",
        fifthImg: "/productImg5.svg",
        carDetails: "Car Details",
        more: "Show all",
        dropImg: "/downdrop.svg",
        updropImg: "/dropup.svg",
        reviews: "Reviews (0)",
        hide: true,
        isSold: false,
        specs: {
          eyeImg: "/eye.svg",
          eyeText: "19,000 Views",
          promoteButton: "Promoted",
          postedText: "Posted on March 19th 2023",
          titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
          locationIcon: "/bluLoc.svg",
          location: "Abule-Egba, Lagos",
          carImg: "/car.svg",
          dUsed: "Local Used",
          auto: "Automatic",
          dAuto: "Automatic",
          autoImg: "/automatic.svg",
          meterImg: "/meter.svg",
          meterText: "9500km",
          make: "Make",
          makeName: "Toyota",
          model: "Model",
          modelName: "2.4 XLE",
          manufacturing: "Manufacturing Year",
          factoryYear: "2008",
          interior: "Interior Color",
          interiorColor: "Black",
          condition: "Condition",
          conditionTitle: "No Faults",
          color: "Color",
          colorType: "Blue",
          seatNo: "No of seats",
          seatCount: "4",
          fuelType: "Fuel Type",
          eletric: "Eletric",
          moreInfo: "More Info",
          infoDescription: "Neatly used Toyota Camry 2.4 XLE 2008. Blue in color and in good condition. Here are some features in the car: Air Conditioning, AM/FM Radio, CD Player, Alloy Wheels, Airbags, Armrests, Cruise Control, Cup Holders, Electric Mirrors, Electric Windows, Front Fog Lamps, Leather Seats, LED Headlights, Parking Assist, Parking Sensors, Sunroof, Traction Control, Xenon Lights",
          storeAdd: "Store Address",
          locationImg: "/location.svg",
          location: "Ajah - Lagos State",
          locationDetails: "24, Shola Martins Streets, Ajah, Lagos",
          deliveryImg: "/truck.svg",
          deliveryBtn: "No delivery",
          workingHour: "Working Hours",
          days: ["Mon", "Tue", "Wed", "Fri"],
          clockImg: "/clock.svg",
          openingHours: "8:30am - 11:00pm",
          availability: "Opened",
          share: "Share",
          whatappImg: "/Whatapp.svg",
          linkedlnImg: "/linkedin.svg",
          facebookImg: "/facebook.svg",
          instaImg: "/gram.svg",
          tiktokImg: "/tiktok.svg",
          twitterImg: "/twitter.svg",
          suggestions: "Suggested For You",
          image: "/benz.svg",
          sideImg: "/sideman.svg",
          vipImg: "/enterprise.svg",
          price: "₦8,000,000",
          standard: "Toyota Camry 2.4 XLE 2008 Blue",
          description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
          descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM"
         }
      },
      {
         id: "9",
        image: "/house.svg",
        sideImg: "/sideman.svg",
        vipImg: "/vip.svg",
        price: "₦28,000",
        dayPrice: "per day",
        standard: "Standard studio apartment per day",
        descriptionHouse: "Very Clean and comfortable area to spend your weekends or holiday with...",
        locationImg: "/location.svg",
        location: "Egbeda, Lagos",
        lUsed: "Local Used",
        auto: "Automatic"
    },
    {
         id: "10",
        image: "/house.svg",
        sideImg: "/sideman.svg",
        vipImg: "/vip.svg",
        price: "₦28,000",
        dayPrice: "per day",
        standard: "Standard studio apartment per day",
        descriptionHouse: "Very Clean and comfortable area to spend your weekends or holiday with...",
        locationImg: "/location.svg",
        location: "Egbeda, Lagos",
        lUsed: "Local Used",
        auto: "Automatic"
    },
    {
         id: "11",
        image: "/benz.svg",
        sideImg: "/sideman.svg",
        vipImg: "/enterprise.svg",
        price: "₦8,000,000",
        standard: "Toyota Camry 2.4 XLE 2008 Blue",
        description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
        descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM",
        locationImg: "/location.svg",
        location: "Abule-Egba, Lagos",
        lUsed: "Local Used",
        auto: "Automatic",
        carImg: "/car.svg",
        dUsed: "Local Used",
        auto: "Automatic",
        dAuto: "Automatic",
        autoImg: "/automatic.svg",
        meterImg: "/meter.svg",
        meterText: "9500km",
        home: "Home",
        cars: "Cars",
        titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
        bookMark: "/bookmark.svg",
        shareIcon: "/share.svg",
        firstImg: "/productImg.svg",
        secondImg: "/productImg2.svg",
        thirdImg: "/productImg3.svg",
        fourthImg: "/productImg4.svg",
        fifthImg: "/productImg5.svg",
        carDetails: "Car Details",
        more: "Show all",
        dropImg: "/downdrop.svg",
        updropImg: "/dropup.svg",
        reviews: "Reviews (0)",
        hide: true,
        isSold: true,
        specs: {
          eyeImg: "/eye.svg",
          eyeText: "19,000 Views",
          promoteButton: "Promoted",
          postedText: "Posted on March 19th 2023",
          titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
          locationIcon: "/bluLoc.svg",
          location: "Abule-Egba, Lagos",
          carImg: "/car.svg",
          dUsed: "Local Used",
          auto: "Automatic",
          dAuto: "Automatic",
          autoImg: "/automatic.svg",
          meterImg: "/meter.svg",
          meterText: "9500km",
          make: "Make",
          makeName: "Toyota",
          model: "Model",
          modelName: "2.4 XLE",
          manufacturing: "Manufacturing Year",
          factoryYear: "2008",
          interior: "Interior Color",
          interiorColor: "Black",
          condition: "Condition",
          conditionTitle: "No Faults",
          color: "Color",
          colorType: "Blue",
          seatNo: "No of seats",
          seatCount: "4",
          fuelType: "Fuel Type",
          eletric: "Eletric",
          moreInfo: "More Info",
          infoDescription: "Neatly used Toyota Camry 2.4 XLE 2008. Blue in color and in good condition. Here are some features in the car: Air Conditioning, AM/FM Radio, CD Player, Alloy Wheels, Airbags, Armrests, Cruise Control, Cup Holders, Electric Mirrors, Electric Windows, Front Fog Lamps, Leather Seats, LED Headlights, Parking Assist, Parking Sensors, Sunroof, Traction Control, Xenon Lights",
          storeAdd: "Store Address",
          locationImg: "/location.svg",
          location: "Ajah - Lagos State",
          locationDetails: "24, Shola Martins Streets, Ajah, Lagos",
          deliveryImg: "/truck.svg",
          deliveryBtn: "No delivery",
          workingHour: "Working Hours",
          days: ["Mon", "Tue", "Wed", "Fri"],
          clockImg: "/clock.svg",
          openingHours: "8:30am - 11:00pm",
          availability: "Opened",
          share: "Share",
          whatappImg: "/Whatapp.svg",
          linkedlnImg: "/linkedin.svg",
          facebookImg: "/facebook.svg",
          instaImg: "/gram.svg",
          tiktokImg: "/tiktok.svg",
          twitterImg: "/twitter.svg",
          suggestions: "Suggested For You",
          image: "/benz.svg",
          sideImg: "/sideman.svg",
          vipImg: "/enterprise.svg",
          price: "₦8,000,000",
          standard: "Toyota Camry 2.4 XLE 2008 Blue",
          description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
          descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM"
         }
      },
      {
        id: "12",
        image: "/benz.svg",
        sideImg: "/sideman.svg",
        vipImg: "/enterprise.svg",
        price: "₦8,000,000",
        standard: "Toyota Camry 2.4 XLE 2008 Blue",
        description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
        descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM",
        locationImg: "/location.svg",
        location: "Abule-Egba, Lagos",
        lUsed: "Local Used",
        carImg: "/car.svg",
        dUsed: "Local Used",
        auto: "Automatic",
        dAuto: "Automatic",
        autoImg: "/automatic.svg",
        meterImg: "/meter.svg",
        meterText: "9500km",
        home: "Home",
        cars: "Cars",
        titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
        bookMark: "/bookmark.svg",
        shareIcon: "/share.svg",
        firstImg: "/productImg.svg",
        secondImg: "/productImg2.svg",
        thirdImg: "/productImg3.svg",
        fourthImg: "/productImg4.svg",
        fifthImg: "/productImg5.svg",
        carDetails: "Car Details",
        more: "Show all",
        dropImg: "/downdrop.svg",
        updropImg: "/dropup.svg",
        reviews: "Reviews (0)",
        hide: true,
        isSold: false,
        specs: {
          eyeImg: "/eye.svg",
          eyeText: "19,000 Views",
          promoteButton: "Promoted",
          postedText: "Posted on March 19th 2023",
          titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
          locationIcon: "/bluLoc.svg",
          location: "Abule-Egba, Lagos",
          carImg: "/car.svg",
          dUsed: "Local Used",
          auto: "Automatic",
          dAuto: "Automatic",
          autoImg: "/automatic.svg",
          meterImg: "/meter.svg",
          meterText: "9500km",
          make: "Make",
          makeName: "Toyota",
          model: "Model",
          modelName: "2.4 XLE",
          manufacturing: "Manufacturing Year",
          factoryYear: "2008",
          interior: "Interior Color",
          interiorColor: "Black",
          condition: "Condition",
          conditionTitle: "No Faults",
          color: "Color",
          colorType: "Blue",
          seatNo: "No of seats",
          seatCount: "4",
          fuelType: "Fuel Type",
          eletric: "Eletric",
          moreInfo: "More Info",
          infoDescription: "Neatly used Toyota Camry 2.4 XLE 2008. Blue in color and in good condition. Here are some features in the car: Air Conditioning, AM/FM Radio, CD Player, Alloy Wheels, Airbags, Armrests, Cruise Control, Cup Holders, Electric Mirrors, Electric Windows, Front Fog Lamps, Leather Seats, LED Headlights, Parking Assist, Parking Sensors, Sunroof, Traction Control, Xenon Lights",
          storeAdd: "Store Address",
          locationImg: "/location.svg",
          location: "Ajah - Lagos State",
          locationDetails: "24, Shola Martins Streets, Ajah, Lagos",
          deliveryImg: "/truck.svg",
          deliveryBtn: "No delivery",
          workingHour: "Working Hours",
          days: ["Mon", "Tue", "Wed", "Fri"],
          clockImg: "/clock.svg",
          openingHours: "8:30am - 11:00pm",
          availability: "Opened",
          share: "Share",
          whatappImg: "/Whatapp.svg",
          linkedlnImg: "/linkedin.svg",
          facebookImg: "/facebook.svg",
          instaImg: "/gram.svg",
          tiktokImg: "/tiktok.svg",
          twitterImg: "/twitter.svg",
          suggestions: "Suggested For You",
          image: "/benz.svg",
          sideImg: "/sideman.svg",
          vipImg: "/enterprise.svg",
          price: "₦8,000,000",
          standard: "Toyota Camry 2.4 XLE 2008 Blue",
          description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
          descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM"
         }
      },
      {
        id: "13",
        image: "/house.svg",
        sideImg: "/nonVip.svg",
        price: "₦28,000",
        dayPrice: "per day",
        standard: "Standard studio apartment per day",
        descriptionHouse: "Very Clean and comfortable area to spend your weekends or holiday with...",
        locationImg: "/location.svg",
        location: "Egbeda, Lagos",
        lUsed: "Local Used",
        auto: "Automatic"
    },
    {
        id: "14",
        image: "/house.svg",
        sideImg: "/nonVip.svg",
        price: "₦28,000",
        dayPrice: "per day",
        standard: "Standard studio apartment per day",
        descriptionHouse: "Very Clean and comfortable area to spend your weekends or holiday with...",
        locationImg: "/location.svg",
        location: "Egbeda, Lagos",
        lUsed: "Local Used",
        auto: "Automatic"
    },
    {
        id: "15",
        image: "/benz.svg",
        sideImg: "/nonVip.svg",
        price: "₦8,000,000",
        standard: "Toyota Camry 2.4 XLE 2008 Blue",
        description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
        descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM",
        locationImg: "/location.svg",
        location: "Abule-Egba, Lagos",
        lUsed: "Local Used",
        auto: "Automatic",
        carImg: "/car.svg",
        dUsed: "Local Used",
        auto: "Automatic",
        dAuto: "Automatic",
        autoImg: "/automatic.svg",
        meterImg: "/meter.svg",
        meterText: "9500km",
        home: "Home",
        cars: "Cars",
        titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
        bookMark: "/bookmark.svg",
        shareIcon: "/share.svg",
        firstImg: "/productImg.svg",
        secondImg: "/productImg2.svg",
        thirdImg: "/productImg3.svg",
        fourthImg: "/productImg4.svg",
        fifthImg: "/productImg5.svg",
        carDetails: "Car Details",
        more: "Show all",
        dropImg: "/downdrop.svg",
        updropImg: "/dropup.svg",
        reviews: "Reviews (0)",
        hide: true,
        isSold: true,
        specs: {
          eyeImg: "/eye.svg",
          eyeText: "19,000 Views",
          promoteButton: "Promoted",
          postedText: "Posted on March 19th 2023",
          titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
          locationIcon: "/bluLoc.svg",
          location: "Abule-Egba, Lagos",
          carImg: "/car.svg",
          dUsed: "Local Used",
          auto: "Automatic",
          dAuto: "Automatic",
          autoImg: "/automatic.svg",
          meterImg: "/meter.svg",
          meterText: "9500km",
          make: "Make",
          makeName: "Toyota",
          model: "Model",
          modelName: "2.4 XLE",
          manufacturing: "Manufacturing Year",
          factoryYear: "2008",
          interior: "Interior Color",
          interiorColor: "Black",
          condition: "Condition",
          conditionTitle: "No Faults",
          color: "Color",
          colorType: "Blue",
          seatNo: "No of seats",
          seatCount: "4",
          fuelType: "Fuel Type",
          eletric: "Eletric",
          moreInfo: "More Info",
          infoDescription: "Neatly used Toyota Camry 2.4 XLE 2008. Blue in color and in good condition. Here are some features in the car: Air Conditioning, AM/FM Radio, CD Player, Alloy Wheels, Airbags, Armrests, Cruise Control, Cup Holders, Electric Mirrors, Electric Windows, Front Fog Lamps, Leather Seats, LED Headlights, Parking Assist, Parking Sensors, Sunroof, Traction Control, Xenon Lights",
          storeAdd: "Store Address",
          locationImg: "/location.svg",
          location: "Ajah - Lagos State",
          locationDetails: "24, Shola Martins Streets, Ajah, Lagos",
          deliveryImg: "/truck.svg",
          deliveryBtn: "No delivery",
          workingHour: "Working Hours",
          days: ["Mon", "Tue", "Wed", "Fri"],
          clockImg: "/clock.svg",
          openingHours: "8:30am - 11:00pm",
          availability: "Opened",
          share: "Share",
          whatappImg: "/Whatapp.svg",
          linkedlnImg: "/linkedin.svg",
          facebookImg: "/facebook.svg",
          instaImg: "/gram.svg",
          tiktokImg: "/tiktok.svg",
          twitterImg: "/twitter.svg",
          suggestions: "Suggested For You",
          image: "/benz.svg",
          sideImg: "/sideman.svg",
          vipImg: "/enterprise.svg",
          price: "₦8,000,000",
          standard: "Toyota Camry 2.4 XLE 2008 Blue",
          description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
          descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM"
         }
      },
      {
        id: "16",
        image: "/benz.svg",
        sideImg: "/nonVip.svg",
        price: "₦8,000,000",
        standard: "Toyota Camry 2.4 XLE 2008 Blue",
        description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
        descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM",
        locationImg: "/location.svg",
        location: "Abule-Egba, Lagos",
        lUsed: "Local Used",
        auto: "Automatic",
        carImg: "/car.svg",
        dUsed: "Local Used",
        auto: "Automatic",
        dAuto: "Automatic",
        autoImg: "/automatic.svg",
        meterImg: "/meter.svg",
        meterText: "9500km",
        home: "Home",
        cars: "Cars",
        titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
        bookMark: "/bookmark.svg",
        shareIcon: "/share.svg",
        firstImg: "/productImg.svg",
        secondImg: "/productImg2.svg",
        thirdImg: "/productImg3.svg",
        fourthImg: "/productImg4.svg",
        fifthImg: "/productImg5.svg",
        carDetails: "Car Details",
        more: "Show all",
        dropImg: "/downdrop.svg",
        updropImg: "/dropup.svg",
        reviews: "Reviews (0)",
        hide: true,
        isSold: false,
        specs: {
          eyeImg: "/eye.svg",
          eyeText: "19,000 Views",
          promoteButton: "Promoted",
          postedText: "Posted on March 19th 2023",
          titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
          locationIcon: "/bluLoc.svg",
          location: "Abule-Egba, Lagos",
          carImg: "/car.svg",
          dUsed: "Local Used",
          auto: "Automatic",
          dAuto: "Automatic",
          autoImg: "/automatic.svg",
          meterImg: "/meter.svg",
          meterText: "9500km",
          make: "Make",
          makeName: "Toyota",
          model: "Model",
          modelName: "2.4 XLE",
          manufacturing: "Manufacturing Year",
          factoryYear: "2008",
          interior: "Interior Color",
          interiorColor: "Black",
          condition: "Condition",
          conditionTitle: "No Faults",
          color: "Color",
          colorType: "Blue",
          seatNo: "No of seats",
          seatCount: "4",
          fuelType: "Fuel Type",
          eletric: "Eletric",
          moreInfo: "More Info",
          infoDescription: "Neatly used Toyota Camry 2.4 XLE 2008. Blue in color and in good condition. Here are some features in the car: Air Conditioning, AM/FM Radio, CD Player, Alloy Wheels, Airbags, Armrests, Cruise Control, Cup Holders, Electric Mirrors, Electric Windows, Front Fog Lamps, Leather Seats, LED Headlights, Parking Assist, Parking Sensors, Sunroof, Traction Control, Xenon Lights",
          storeAdd: "Store Address",
          locationImg: "/location.svg",
          location: "Ajah - Lagos State",
          locationDetails: "24, Shola Martins Streets, Ajah, Lagos",
          deliveryImg: "/truck.svg",
          deliveryBtn: "No delivery",
          workingHour: "Working Hours",
          days: ["Mon", "Tue", "Wed", "Fri"],
          clockImg: "/clock.svg",
          openingHours: "8:30am - 11:00pm",
          availability: "Opened",
          share: "Share",
          whatappImg: "/Whatapp.svg",
          linkedlnImg: "/linkedin.svg",
          facebookImg: "/facebook.svg",
          instaImg: "/gram.svg",
          tiktokImg: "/tiktok.svg",
          twitterImg: "/twitter.svg",
          suggestions: "Suggested For You",
          image: "/benz.svg",
          sideImg: "/sideman.svg",
          vipImg: "/enterprise.svg",
          price: "₦8,000,000",
          standard: "Toyota Camry 2.4 XLE 2008 Blue",
          description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
          descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM"
         }
      },
      {
         id: "17",
        image: "/house.svg",
        sideImg: "/nonVip.svg",
        price: "₦28,000",
        dayPrice: "per day",
        standard: "Standard studio apartment per day",
        descriptionHouse: "Very Clean and comfortable area to spend your weekends or holiday with...",
        locationImg: "/location.svg",
        location: "Egbeda, Lagos",
        lUsed: "Local Used",
        auto: "Automatic"
    },
    {
        id: "18",
        image: "/house.svg",
        sideImg: "/nonVip.svg",
        price: "₦28,000",
        dayPrice: "per day",
        standard: "Standard studio apartment per day",
        descriptionHouse: "Very Clean and comfortable area to spend your weekends or holiday with...",
        locationImg: "/location.svg",
        location: "Egbeda, Lagos",
        lUsed: "Local Used",
        auto: "Automatic"
    },
    {
         id: "19",
        image: "/benz.svg",
        sideImg: "/nonVip.svg",
        price: "₦8,000,000",
        standard: "Toyota Camry 2.4 XLE 2008 Blue",
        description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
        descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM",
        locationImg: "/location.svg",
        location: "Abule-Egba, Lagos",
        lUsed: "Local Used",
        auto: "Automatic",
        carImg: "/car.svg",
        dUsed: "Local Used",
        auto: "Automatic",
        dAuto: "Automatic",
        autoImg: "/automatic.svg",
        meterImg: "/meter.svg",
        meterText: "9500km",
        home: "Home",
        cars: "Cars",
        titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
        bookMark: "/bookmark.svg",
        shareIcon: "/share.svg",
        firstImg: "/productImg.svg",
        secondImg: "/productImg2.svg",
        thirdImg: "/productImg3.svg",
        fourthImg: "/productImg4.svg",
        fifthImg: "/productImg5.svg",
        carDetails: "Car Details",
        more: "Show all",
        dropImg: "/downdrop.svg",
        updropImg: "/dropup.svg",
        reviews: "Reviews (0)",
        hide: true,
        isSold: true,
        specs: {
          eyeImg: "/eye.svg",
          eyeText: "19,000 Views",
          promoteButton: "Promoted",
          postedText: "Posted on March 19th 2023",
          titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
          locationIcon: "/bluLoc.svg",
          location: "Abule-Egba, Lagos",
          carImg: "/car.svg",
          dUsed: "Local Used",
          auto: "Automatic",
          dAuto: "Automatic",
          autoImg: "/automatic.svg",
          meterImg: "/meter.svg",
          meterText: "9500km",
          make: "Make",
          makeName: "Toyota",
          model: "Model",
          modelName: "2.4 XLE",
          manufacturing: "Manufacturing Year",
          factoryYear: "2008",
          interior: "Interior Color",
          interiorColor: "Black",
          condition: "Condition",
          conditionTitle: "No Faults",
          color: "Color",
          colorType: "Blue",
          seatNo: "No of seats",
          seatCount: "4",
          fuelType: "Fuel Type",
          eletric: "Eletric",
          moreInfo: "More Info",
          infoDescription: "Neatly used Toyota Camry 2.4 XLE 2008. Blue in color and in good condition. Here are some features in the car: Air Conditioning, AM/FM Radio, CD Player, Alloy Wheels, Airbags, Armrests, Cruise Control, Cup Holders, Electric Mirrors, Electric Windows, Front Fog Lamps, Leather Seats, LED Headlights, Parking Assist, Parking Sensors, Sunroof, Traction Control, Xenon Lights",
          storeAdd: "Store Address",
          locationImg: "/location.svg",
          location: "Ajah - Lagos State",
          locationDetails: "24, Shola Martins Streets, Ajah, Lagos",
          deliveryImg: "/truck.svg",
          deliveryBtn: "No delivery",
          workingHour: "Working Hours",
          days: ["Mon", "Tue", "Wed", "Fri"],
          clockImg: "/clock.svg",
          openingHours: "8:30am - 11:00pm",
          availability: "Opened",
          share: "Share",
          whatappImg: "/Whatapp.svg",
          linkedlnImg: "/linkedin.svg",
          facebookImg: "/facebook.svg",
          instaImg: "/gram.svg",
          tiktokImg: "/tiktok.svg",
          twitterImg: "/twitter.svg",
          suggestions: "Suggested For You",
          image: "/benz.svg",
          sideImg: "/sideman.svg",
          vipImg: "/enterprise.svg",
          price: "₦8,000,000",
          standard: "Toyota Camry 2.4 XLE 2008 Blue",
          description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
          descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM"
         }
      },
      {
        id: "20",
        image: "/benz.svg",
        sideImg: "/nonVip.svg",
        price: "₦8,000,000",
        standard: "Toyota Camry 2.4 XLE 2008 Blue",
        description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
        descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM",
        locationImg: "/location.svg",
        location: "Abule-Egba, Lagos",
        lUsed: "Local Used",
        auto: "Automatic",
        carImg: "/car.svg",
        dUsed: "Local Used",
        auto: "Automatic",
        dAuto: "Automatic",
        autoImg: "/automatic.svg",
        meterImg: "/meter.svg",
        meterText: "9500km",
        home: "Home",
        cars: "Cars",
        titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
        bookMark: "/bookmark.svg",
        shareIcon: "/share.svg",
        firstImg: "/productImg.svg",
        secondImg: "/productImg2.svg",
        thirdImg: "/productImg3.svg",
        fourthImg: "/productImg4.svg",
        fifthImg: "/productImg5.svg",
        carDetails: "Car Details",
        more: "Show all",
        dropImg: "/downdrop.svg",
        updropImg: "/dropup.svg",
        reviews: "Reviews (0)",
        hide: true,
        isSold: false,
        specs: {
          eyeImg: "/eye.svg",
          eyeText: "19,000 Views",
          promoteButton: "Promoted",
          postedText: "Posted on March 19th 2023",
          titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
          locationIcon: "/bluLoc.svg",
          location: "Abule-Egba, Lagos",
          carImg: "/car.svg",
          dUsed: "Local Used",
          auto: "Automatic",
          dAuto: "Automatic",
          autoImg: "/automatic.svg",
          meterImg: "/meter.svg",
          meterText: "9500km",
          make: "Make",
          makeName: "Toyota",
          model: "Model",
          modelName: "2.4 XLE",
          manufacturing: "Manufacturing Year",
          factoryYear: "2008",
          interior: "Interior Color",
          interiorColor: "Black",
          condition: "Condition",
          conditionTitle: "No Faults",
          color: "Color",
          colorType: "Blue",
          seatNo: "No of seats",
          seatCount: "4",
          fuelType: "Fuel Type",
          eletric: "Eletric",
          moreInfo: "More Info",
          infoDescription: "Neatly used Toyota Camry 2.4 XLE 2008. Blue in color and in good condition. Here are some features in the car: Air Conditioning, AM/FM Radio, CD Player, Alloy Wheels, Airbags, Armrests, Cruise Control, Cup Holders, Electric Mirrors, Electric Windows, Front Fog Lamps, Leather Seats, LED Headlights, Parking Assist, Parking Sensors, Sunroof, Traction Control, Xenon Lights",
          storeAdd: "Store Address",
          locationImg: "/location.svg",
          location: "Ajah - Lagos State",
          locationDetails: "24, Shola Martins Streets, Ajah, Lagos",
          deliveryImg: "/truck.svg",
          deliveryBtn: "No delivery",
          workingHour: "Working Hours",
          days: ["Mon", "Tue", "Wed", "Fri"],
          clockImg: "/clock.svg",
          openingHours: "8:30am - 11:00pm",
          availability: "Opened",
          share: "Share",
          whatappImg: "/Whatapp.svg",
          linkedlnImg: "/linkedin.svg",
          facebookImg: "/facebook.svg",
          instaImg: "/gram.svg",
          tiktokImg: "/tiktok.svg",
          twitterImg: "/twitter.svg",
          suggestions: "Suggested For You",
          image: "/benz.svg",
          sideImg: "/sideman.svg",
          vipImg: "/enterprise.svg",
          price: "₦8,000,000",
          standard: "Toyota Camry 2.4 XLE 2008 Blue",
          description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
          descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM"
         }
      },
      {
         id: "21",
        image: "/house.svg",
        sideImg: "/nonVip.svg",
        price: "₦28,000",
        dayPrice: "per day",
        standard: "Standard studio apartment per day",
        descriptionHouse: "Very Clean and comfortable area to spend your weekends or holiday with...",
        locationImg: "/location.svg",
        location: "Egbeda, Lagos",
        lUsed: "Local Used",
        auto: "Automatic"
    },
    {
         id: "22",
        image: "/house.svg",
        sideImg: "/nonVip.svg",
        price: "₦28,000",
        dayPrice: "per day",
        standard: "Standard studio apartment per day",
        descriptionHouse: "Very Clean and comfortable area to spend your weekends or holiday with...",
        locationImg: "/location.svg",
        location: "Egbeda, Lagos",
        lUsed: "Local Used",
        auto: "Automatic"
    },
    {
         id: "23",
        image: "/benz.svg",
        sideImg: "/nonVip.svg",
        price: "₦8,000,000",
        standard: "Toyota Camry 2.4 XLE 2008 Blue",
        description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
        descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM",
        locationImg: "/location.svg",
        location: "Abule-Egba, Lagos",
        lUsed: "Local Used",
        auto: "Automatic",
        carImg: "/car.svg",
        dUsed: "Local Used",
        auto: "Automatic",
        dAuto: "Automatic",
        autoImg: "/automatic.svg",
        meterImg: "/meter.svg",
        meterText: "9500km",
        home: "Home",
        cars: "Cars",
        titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
        bookMark: "/bookmark.svg",
        shareIcon: "/share.svg",
        firstImg: "/productImg.svg",
        secondImg: "/productImg2.svg",
        thirdImg: "/productImg3.svg",
        fourthImg: "/productImg4.svg",
        fifthImg: "/productImg5.svg",
        carDetails: "Car Details",
        more: "Show all",
        dropImg: "/downdrop.svg",
        updropImg: "/dropup.svg",
        reviews: "Reviews (0)",
        hide: true,
        isSold: true,
        specs: {
          eyeImg: "/eye.svg",
          eyeText: "19,000 Views",
          promoteButton: "Promoted",
          postedText: "Posted on March 19th 2023",
          titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
          locationIcon: "/bluLoc.svg",
          location: "Abule-Egba, Lagos",
          carImg: "/car.svg",
          dUsed: "Local Used",
          auto: "Automatic",
          dAuto: "Automatic",
          autoImg: "/automatic.svg",
          meterImg: "/meter.svg",
          meterText: "9500km",
          make: "Make",
          makeName: "Toyota",
          model: "Model",
          modelName: "2.4 XLE",
          manufacturing: "Manufacturing Year",
          factoryYear: "2008",
          interior: "Interior Color",
          interiorColor: "Black",
          condition: "Condition",
          conditionTitle: "No Faults",
          color: "Color",
          colorType: "Blue",
          seatNo: "No of seats",
          seatCount: "4",
          fuelType: "Fuel Type",
          eletric: "Eletric",
          moreInfo: "More Info",
          infoDescription: "Neatly used Toyota Camry 2.4 XLE 2008. Blue in color and in good condition. Here are some features in the car: Air Conditioning, AM/FM Radio, CD Player, Alloy Wheels, Airbags, Armrests, Cruise Control, Cup Holders, Electric Mirrors, Electric Windows, Front Fog Lamps, Leather Seats, LED Headlights, Parking Assist, Parking Sensors, Sunroof, Traction Control, Xenon Lights",
          storeAdd: "Store Address",
          locationImg: "/location.svg",
          location: "Ajah - Lagos State",
          locationDetails: "24, Shola Martins Streets, Ajah, Lagos",
          deliveryImg: "/truck.svg",
          deliveryBtn: "No delivery",
          workingHour: "Working Hours",
          days: ["Mon", "Tue", "Wed", "Fri"],
          clockImg: "/clock.svg",
          openingHours: "8:30am - 11:00pm",
          availability: "Opened",
          share: "Share",
          whatappImg: "/Whatapp.svg",
          linkedlnImg: "/linkedin.svg",
          facebookImg: "/facebook.svg",
          instaImg: "/gram.svg",
          tiktokImg: "/tiktok.svg",
          twitterImg: "/twitter.svg",
          suggestions: "Suggested For You",
          image: "/benz.svg",
          sideImg: "/sideman.svg",
          vipImg: "/enterprise.svg",
          price: "₦8,000,000",
          standard: "Toyota Camry 2.4 XLE 2008 Blue",
          description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
          descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM"
         }
      },
      {
        id: "24",
        image: "/benz.svg",
        sideImg: "/nonVip.svg",
        price: "₦8,000,000",
        standard: "Toyota Camry 2.4 XLE 2008 Blue",
        description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
        descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM",
        locationImg: "/location.svg",
        location: "Abule-Egba, Lagos",
        lUsed: "Local Used",
        auto: "Automatic",
        carImg: "/car.svg",
        dUsed: "Local Used",
        auto: "Automatic",
        dAuto: "Automatic",
        autoImg: "/automatic.svg",
        meterImg: "/meter.svg",
        meterText: "9500km",
        home: "Home",
        cars: "Cars",
        titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
        bookMark: "/bookmark.svg",
        shareIcon: "/share.svg",
        firstImg: "/productImg.svg",
        secondImg: "/productImg2.svg",
        thirdImg: "/productImg3.svg",
        fourthImg: "/productImg4.svg",
        fifthImg: "/productImg5.svg",
        carDetails: "Car Details",
        more: "Show all",
        dropImg: "/downdrop.svg",
        updropImg: "/dropup.svg",
        reviews: "Reviews (0)",
        hide: true,
        isSold: false,
        specs: {
          eyeImg: "/eye.svg",
          eyeText: "19,000 Views",
          promoteButton: "Promoted",
          postedText: "Posted on March 19th 2023",
          titleProduct: "Toyota Camry 2.4 XLE 2008 Blue",
          locationIcon: "/bluLoc.svg",
          location: "Abule-Egba, Lagos",
          carImg: "/car.svg",
          dUsed: "Local Used",
          auto: "Automatic",
          dAuto: "Automatic",
          autoImg: "/automatic.svg",
          meterImg: "/meter.svg",
          meterText: "9500km",
          make: "Make",
          makeName: "Toyota",
          model: "Model",
          modelName: "2.4 XLE",
          manufacturing: "Manufacturing Year",
          factoryYear: "2008",
          interior: "Interior Color",
          interiorColor: "Black",
          condition: "Condition",
          conditionTitle: "No Faults",
          color: "Color",
          colorType: "Blue",
          seatNo: "No of seats",
          seatCount: "4",
          fuelType: "Fuel Type",
          eletric: "Eletric",
          moreInfo: "More Info",
          infoDescription: "Neatly used Toyota Camry 2.4 XLE 2008. Blue in color and in good condition. Here are some features in the car: Air Conditioning, AM/FM Radio, CD Player, Alloy Wheels, Airbags, Armrests, Cruise Control, Cup Holders, Electric Mirrors, Electric Windows, Front Fog Lamps, Leather Seats, LED Headlights, Parking Assist, Parking Sensors, Sunroof, Traction Control, Xenon Lights",
          storeAdd: "Store Address",
          locationImg: "/location.svg",
          location: "Ajah - Lagos State",
          locationDetails: "24, Shola Martins Streets, Ajah, Lagos",
          deliveryImg: "/truck.svg",
          deliveryBtn: "No delivery",
          workingHour: "Working Hours",
          days: ["Mon", "Tue", "Wed", "Fri"],
          clockImg: "/clock.svg",
          openingHours: "8:30am - 11:00pm",
          availability: "Opened",
          share: "Share",
          whatappImg: "/Whatapp.svg",
          linkedlnImg: "/linkedin.svg",
          facebookImg: "/facebook.svg",
          instaImg: "/gram.svg",
          tiktokImg: "/tiktok.svg",
          twitterImg: "/twitter.svg",
          suggestions: "Suggested For You",
          image: "/benz.svg",
          sideImg: "/sideman.svg",
          vipImg: "/enterprise.svg",
          price: "₦8,000,000",
          standard: "Toyota Camry 2.4 XLE 2008 Blue",
          description: "Very clean and sound Toyota, excellent condition. You can come and check it...",
          descriptionTwo: "Very clean and sound Toyota, excellent condition. You can come and check it out. If you are interested shoot me a DM"
         }
      },
   ]
}

export const footerData = [
   {
    title: "Company",
    links: [
      { label: "About Us", href: "/About-Us"},
      { label: "Terms & Conditions", href: "/Terms" },
      { label: "Privacy Policy", href: "/privacy-policy" },
      { label: "Billing Policy", href: "/billings" },
    ]
   },
   {
    title: "Support",
    links: [
      { label: "Contact-Us", href: "/contact" },
      { label: "FAQ", href: "/Faq" },
      { label: "Safety Tip", href: "/safety-tip"},
      { label: "support@tenaly.com", href: "/support" },
    ]
   },
   {
    title: "Social Link",
    socialIcons: [
      { icon: FaYoutube, link: "#", color: "#FF0000" },
      { icon: FaLinkedinIn, link: "#", color: "#006699" },
      { icon: FaFacebookF, link: "#", color: "#337FFF" },
      { icon: FaInstagram, link: "#", color: "#8C3AAA" },
      { icon: FaTiktok, link: "#", color: "#000000" },
      { icon: FaXTwitter, link: "#", color: "#FFFFFF" },
    ],
   }
  ]